#!/usr/bin/env python3

import socket

if __name__ == '__main__':
    s = socket.socket()
    s.connect(('127.0.0.1', 2525))
    res = s.recv(512)
    print(res.decode())
    s.send(b'HELO I am a funny man\r\n')
    print(s.recv(512).decode())
    s.send(b'MAIL FROM:<dgolding@phlexglobal.com>\r\n')
    print(s.recv(512).decode())
    s.send(b'RCPT TO:<dgolding@phlexglobal.com>\r\n')
    print(s.recv(512).decode())
    s.send(b'RCPT TO:<dgolding@phlexglobal.com>\r\n')
    print(s.recv(512).decode())
    s.send(b'DATA\r\n')
    print(s.recv(512).decode())
    s.send(b'Dear harry\r\n')
    s.send(b'how are you?\r\n')
    s.send(b'.This is not end of mail\r\n')
    s.send(b'..\r\n')
    s.send(b'Nor that or this. But this:\r\n')
    s.send(b'.\r\n')
    print(s.recv(512).decode())

