#!/usr/bin/env python3

import socket

if __name__ == '__main__':
    s = socket.socket()
    s.connect(('127.0.0.1', 2525))
    res = s.recv(512)
    print(res.decode())
    s.send(b'HELO I am a funny man\r\n')
    print(s.recv(512).decode())
    s.send(b'MAIL FROM:<dgolding@phlexglobal.com>\r\n')
    print(s.recv(512).decode())
    s.send(b'RCPT TO:<dgolding@phlexglobal.com>\r\n')
    print(s.recv(512).decode())
    s.send(b'RCPT TO:<dgolding@phlexglobal.com>\r\n')
    print(s.recv(512).decode())

